export const STAGE_TYPES = {
  AUDIO_CONTEXT: Symbol.for("AUDIO_CONTEXT"),
  EVENT_EMITTER: Symbol.for("EVENT_EMITTER"),
  ELECTRON_STORE: Symbol.for("ELECTRON_STORE"),
  REWIND_SKINS_FOLDER: Symbol.for("REWIND_SKINS_FOLDER"),
};
